"""require external_reference

Revision ID: b332e62ca5a8
Revises: a0f333783b9c
Create Date: 2026-01-29 13:35:51.689538

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b332e62ca5a8"
down_revision: Union[str, Sequence[str], None] = "a0f333783b9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shipments", "external_reference", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shipments", "external_reference", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###
